version: '3.1'
services:
  db:
    build:
      context: ./db/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: icanmining
      MYSQL_PASSWORD: icanmining
    container_name: icanmining-db
    ports:
      - 3307:3306
  app:
    build:
      context: .
      args:
        - app_file
        - app_profile
    container_name: icanmining-app
    depends_on:
      - db
    ports:
      - 8888:8080

